ver 1.1.0
Crizz0/knowledgebase pull request #2
Opened 2021-07-20 17:31 UTC by Mike-on-Tour

2021-07-20 17:34 UTC, Mike-on-Tour commented
Added a preview function to 'post' and 'edit' modes, added logging of editing articles and fixed some issues

2021-07-26 15:16 UTC, Mike-on-Tour commented
Renamed the version to 1.1.0-dev and fixed three issues in main_controller.php

2021-07-27 17:50 UTC, Crizz0 requested changes
Good job! 👍 

Hab nur zwei Kleinigkeiten.

2021-07-27 17:50 UTC, Crizz0 commented on controller/main_controller.php
> +//				$board_url = generate_board_url();
Wenn du es auskommentierst, kannst dus auch gleich entfernen. :)

2021-07-27 17:50 UTC, Crizz0 commented on styles/prosilver/template/preview_article.html
> +						<hr />
```suggestion
						<hr>
```

2021-07-28 06:31 UTC, Crizz0 approved these changes

2021-07-28 06:31 UTC, merged